import type { GitRecipe } from '../types';

export const GIT_RECIPES: GitRecipe[] = [
  {
    id: 'undo-last-commit-soft',
    title: 'Undo last commit (keep changes staged/modified)',
    category: 'commits',
    description: 'Undoes the most recent commit on your current branch but leaves all your file modifications intact in your working tree.',
    command: 'git reset --soft HEAD~1',
    explanation: 'HEAD~1 points to the commit before HEAD. --soft keeps index and working directory untouched so you can re-stage and commit again.',
    tags: ['undo', 'commit', 'soft reset', 'mistake', 'fix message'],
  },
  {
    id: 'undo-last-commit-hard',
    title: 'Undo last commit and discard all changes permanently',
    category: 'commits',
    description: 'Completely destroys the last commit and discards all changes in tracked files since the prior commit.',
    command: 'git reset --hard HEAD~1',
    explanation: 'WARNING: This is destructive. Any uncommitted work or changes in the last commit will be discarded.',
    tags: ['undo', 'discard', 'hard reset', 'destroy'],
  },
  {
    id: 'commit-amend',
    title: 'Amend previous commit (change message or add files)',
    category: 'commits',
    description: 'Combine staged files into the previous commit and optionally update the commit message without creating a new commit.',
    command: 'git commit --amend --no-edit',
    explanation: 'If you want to edit the message instead, run "git commit --amend -m \'new message\'".',
    tags: ['amend', 'edit commit', 'fixup', 'typo'],
  },
  {
    id: 'move-commit-new-branch',
    title: 'Committed to wrong branch (move commit to a new branch)',
    category: 'branches',
    description: 'You accidentally committed to main/master and want to move that commit over to a feature branch.',
    command: 'git branch <new-feature-branch> && git reset --hard HEAD~1 && git checkout <new-feature-branch>',
    explanation: 'Creates the new branch at current commit, rolls back current branch by 1 commit, then switches to the new branch.',
    tags: ['wrong branch', 'move commit', 'branch fix', 'mistake'],
  },
  {
    id: 'rebase-on-main',
    title: 'Rebase current branch on top of latest main',
    category: 'sync',
    description: 'Fetches the latest commits from origin/main and replays your local feature branch commits cleanly on top.',
    command: 'git fetch origin main && git rebase origin/main',
    explanation: 'Maintains a linear commit history. If conflicts occur, resolve them and run "git rebase --continue".',
    tags: ['rebase', 'main', 'sync', 'linear', 'update branch'],
  },
  {
    id: 'delete-merged-branches',
    title: 'Clean up & delete all merged local branches',
    category: 'branches',
    description: 'Removes all local branches that have already been merged into your current branch (excluding main/master).',
    command: 'git branch --merged | grep -vE "^\\*|master|main|dev|staging" | xargs -n 1 git branch -d',
    explanation: 'Safe deletion using "-d" which only deletes branches whose commits are reachable in the current branch.',
    tags: ['cleanup', 'delete branch', 'prune', 'merged'],
  },
  {
    id: 'stash-untracked',
    title: 'Stash all tracked AND untracked / new files',
    category: 'stash',
    description: 'Temporarily stashes everything including untracked new files so your working directory is completely clean.',
    command: 'git stash -u -m "wip-work"',
    explanation: 'The "-u" flag (--include-untracked) ensures newly created files are also safely captured in the stash.',
    tags: ['stash', 'save work', 'untracked', 'clean tree', 'wip'],
  },
  {
    id: 'stash-pop',
    title: 'Apply and drop the most recent stash',
    category: 'stash',
    description: 'Restores your previously stashed changes back into your working tree and removes the stash from the list.',
    command: 'git stash pop',
    explanation: 'If you want to apply without removing from stash list, use "git stash apply".',
    tags: ['stash', 'restore', 'pop', 'wip'],
  },
  {
    id: 'discard-unstaged',
    title: 'Discard all local changes in tracked files',
    category: 'commits',
    description: 'Restores all modified files back to the state of the HEAD commit.',
    command: 'git restore .',
    explanation: 'Replaces old "git checkout -- ." command. To also delete untracked files, run "git clean -fd".',
    tags: ['discard', 'revert', 'restore', 'reset'],
  },
  {
    id: 'abort-conflict',
    title: 'Abort an active merge or rebase during conflict',
    category: 'conflicts',
    description: 'Safely bails out of a problematic merge or rebase and restores your repository to the exact pre-merge state.',
    command: 'git merge --abort || git rebase --abort',
    explanation: 'Completely cancels the in-progress operation without leaving half-merged conflict markers in your code.',
    tags: ['abort', 'conflict', 'bail out', 'cancel merge', 'cancel rebase'],
  },
  {
    id: 'squash-last-n',
    title: 'Interactive rebase to squash last N commits',
    category: 'commits',
    description: 'Combines multiple small "wip" or "fixup" commits into a clean, single commit before opening a pull request.',
    command: 'git rebase -i HEAD~3',
    explanation: 'In the interactive editor, change "pick" to "squash" (or "s") for commits you want to fold into the previous one.',
    tags: ['squash', 'interactive rebase', 'clean history', 'wip'],
  },
  {
    id: 'cherry-pick-commit',
    title: 'Cherry-pick a specific commit from another branch',
    category: 'commits',
    description: 'Applies the changes from a single commit onto your current branch without merging the whole branch.',
    command: 'git cherry-pick <commit-sha>',
    explanation: 'Copies the exact patch of <commit-sha> and creates a new commit on your current branch.',
    tags: ['cherry-pick', 'port commit', 'hotfix', 'patch'],
  },
  {
    id: 'rename-branch',
    title: 'Rename local and remote branch',
    category: 'branches',
    description: 'Renames your current local branch and updates the tracking branch on remote.',
    command: 'git branch -m <new-name> && git push origin -u <new-name> && git push origin --delete <old-name>',
    explanation: 'Renames local branch, pushes new name to remote with upstream tracking, then removes old remote branch.',
    tags: ['rename', 'branch', 'remote', 'move'],
  },
];
